### PR TITLE
Added messages for sensor suite

### PR DESCRIPTION
**Pull request by ItsTimmy**
## Description

- Added the following messages for the sensor suite (See duckietown/dt-duckiebot-interface-dbv2#2):
  - ToFStamped
  - LineFollowerStamped
- Edited EncoderStamped message

All of these messages are currently only used by the `sensor_suite` package added by duckietown/dt-duckiebot-interface-dbv2#2.

## Type of change

Please mark the relevant options with X:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change is constrained only to one package, any interfaces to nodes from other packages are maintained
- [ ] This change is constrained only to packages in this repository, any interfaces to nodes from other repositories are maintained
- [ ] This change required a documentation update
- [ ] This change is only a documentation update
- [ ] This change restructures the repository (at level higher than package level)
- [ ] This change requires a change in the Duckiebook (if yes, please describe and, if possible, make a pull request for an edit in the book and link it here)

## Tests

Please describe all tests ran and their outcome. It is highly recommended that you at least do the tests listed by default, even if you only changed the documentation.

- [X] Made the Duckiebot move with keyboard control
- [X] Visually checked the published camera stream
- [X] Verified that the lane following demo works
- [X] Verified that the indefinite navigation demo works

## Style compliance
Please make sure that all your changes conform to the Duckietown (code style)[link] and code (documentation style)[link] guidelines:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I checked that this pull request is compliant with the Duckietown code style
- [X] I checked that this pull request is compliant with the Duckietown code documentation style

## Next steps
Please describe if you have any questions, comments, or doubts towards the Duckietown software guardians regarding implementation, code style, running tests, documentation, etc.

## FOR THE REVIEWERS
__IMPORTANT:__ DO NOT CHANGE THIS SECTION!

- [ ] Functionality (is the change necessary and is it implemented in the most appropriate way): @liampaull or @afdaniele
- [ ] Integration testing (verify the tests and run additional if necessary): @?
- [ ] Code style compliance: @gibernas
- [ ] Documentation compliance: @aleksandarpetrov

_To the reviewers:_ If you deem necessary, request code edits, more tests, documentation update, or additional reviewing. __Do not review your own code!__

_PR Template, last edit 23 Aug 2019_

### CODE REVIEW

**Comment by ItsTimmy** [comment]
This is ready for review @AmaurX @surirohit

**Comment by afdaniele** [comment]
Redeclaring messages as subset of others is (almost) always a bad idea.
A few points:
- The time you change your sensor/drivers and thus gain access to more data, you will need to change the message definition and all the nodes using it.
- You can't take advantage of pre-existing code (e.g., rviz) to manipulate/use/visualize what's being published, just because your message is now a subset of what those apps normally expect.

**Comment by ItsTimmy** [comment]
@afdaniele Ok, I fixed it. Thanks for the info!

**Comment by liampaull** [comment]
this seems ok to me.

**Comment by ItsTimmy** [comment]
@afdaniele @liampaull Since this has been reviewed and updated, can it be merged? I have a PR open (https://github.com/duckietown/dt-duckiebot-interface-dbv2/pull/2) which I don't want to merge to daffy until it can build using `dt-ros-commons:daffy`.

**Pull request merged**
